service: proplist-auth-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  httpApi:
    id: !ImportValue proplist-api-gateway-HttpApiId
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    AWS_REGION_NAME: ap-southeast-2

functions:
  register:
    handler: src/register.handler
    events:
      - httpApi:
          path: /api/auth/register
          method: POST

  login:
    handler: src/login.handler
    events:
      - httpApi:
          path: /api/auth/login
          method: POST

  verify:
    handler: src/verify.handler
    events:
      - httpApi:
          path: /api/auth/verify
          method: POST

  resendCode:
    handler: src/resendCode.handler
    events:
      - httpApi:
          path: /api/auth/resend-code
          method: POST
