service: proplist-admin-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  httpApi:
    id: !ImportValue proplist-api-gateway-HttpApiId
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    AWS_REGION_NAME: ap-southeast-2

functions:
  listPendingProperties:
    handler: src/listPendingProperties.handler
    events:
      - httpApi:
          path: /api/admin/properties
          method: GET
          authorizer:
            id: ugclgq

  updatePropertyStatus:
    handler: src/updatePropertyStatus.handler
    events:
      - httpApi:
          path: /api/admin/properties/{id}
          method: PATCH
          authorizer:
            id: ugclgq

  listUsers:
    handler: src/listUsers.handler
    events:
      - httpApi:
          path: /api/admin/users
          method: GET
          authorizer:
            id: ugclgq

  updateUser:
    handler: src/updateUser.handler
    events:
      - httpApi:
          path: /api/admin/users/{id}
          method: PATCH
          authorizer:
            id: ugclgq
